# Materials defines the default filter configuration of a quarry. Thus, it also specifies all materials which a quarry
# may mine.
materials:
  STONE: false
  DIORITE: false
  GRAVEL: false
  DIRT: false
  GRANITE: false
  CLAY: false
  COAL_ORE: true
  LAPIS_ORE: true
  REDSTONE_ORE: true
  GOLD_ORE: true
  IRON_ORE: true
  DIAMOND_ORE: true
  EMERALD_ORE: true
  ANDESITE: false
  GRASS_BLOCK: false

# Configure what items can be used to fuel, and how much fuel each is worth.
fuels:
  LAVA_BUCKET: 800
  COAL_BLOCK: 640
  BLAZE_ROD: 96
  COAL: 64
  CHARCOAL: 64